services:
  postgres:
    container_name: local-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pcmacadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
